name: Add New Consultant To Database

on:
  workflow_dispatch:
    inputs:
      cons_number:
        description: 'ИД Консультанта'
        required: true
      last_name:
        description: 'Фамилия'
        required: true
      first_name:
        description: 'Имя'
        required: true
      reg_date:
        description: 'Дата (ГГГГ-ММ-ДД)'
        required: false

jobs:
  send_to_mysql:
    runs-on: ubuntu-latest
    steps:
      - name: Send Data to Python API
        run: |
          curl -X POST "${{ secrets.DB_API_URL }}" \
            -H "Content-Type: application/json" \
            -H "X-Api-Token: ${{ secrets.DB_API_TOKEN }}" \
            -d '{
              "cons_number": "${{ github.event.inputs.cons_number }}",
              "last_name": "${{ github.event.inputs.last_name }}",
              "first_name": "${{ github.event.inputs.first_name }}",
              "reg_date": "${{ github.event.inputs.reg_date }}",
              "status": "new"
            }'
